package it.danielezotta.psalegacy.protocol

import java.util.Locale

/**
 * Local catalog of vehicle alert indicators (bits 0..255 of the trip message's
 * miscIndicatorsAndAlerts mask), extracted verbatim from the original MyPeugeot
 * APK string resources (ShortAlertVehicle_xxx / criticity_xxx). Codes not present
 * in the original app's tables (e.g. 109) resolve to null.
 */
object AlertCatalog {

    data class AlertInfo(
        val titleIt: String,
        val titleEn: String,
        val criticity: String? = null
    )

    /**
     * French titles from the head unit itself: extracted from the SMEG+ 5.43.A.R2
     * firmware (db_alerts.sqlite, jda_alerts table — the 256-bit trip alert mask).
     * Covers bits the original app's catalog lacks (doors, roof, lights, wheels...).
     */
    private val HU_FR: Map<Int, String> = mapOf(
        0 to "Défaut pression huile moteur : arretez le véhicule",
        1 to "Water temperature alarm",
        3 to "Défaut système de freinage : arrêtez le véhicule",
        5 to "Défaut direction assistée : arrêtez le véhicule",
        6 to "Ajustez niveau liquide refroidissement",
        8 to "Ajustez niveau huile moteur",
        10 to "Porte avant gauche ouverte",
        11 to "Porte avant droite ouverte",
        12 to "Porte arrière gauche ouverte",
        13 to "Porte arrière droite ouverte",
        15 to "Coffre ouvert",
        16 to "Lunette arrière ouverte",
        17 to "Défaut système ESP/ASR : arrêtez le véhicule",
        18 to "Défaut charge batterie : arrêtez le véhicule",
        20 to "Présence d'eau dans le filtre à gazoil : faites réparer le véhicule",
        21 to "Faites changer les plaquettes de frein",
        22 to "Niveau carburant faible",
        23 to "Défaut Airbag(s) ou ceinture(s) à prétension",
        25 to "Défaut moteur : Faites réparer le véhicule",
        26 to "Défaut système de freinage ABS : Faites réparer le véhicule",
        27 to "Risque de colmatage filtre à particules : Consultez la notice",
        29 to "Niveau additif FAP trop faible : Faites réparer le véhicule",
        31 to "Défaut suspension : Faites réparer le véhicule",
        32 to "Préchauffage : préventilation désactivé : Niveau de batterie faible",
        33 to "Préchauffage : préventilation désactivé : Niveau de carburant faible",
        34 to "Contrôlez feu STOP central",
        35 to "Défaut mécanisme toit escamotable",
        36 to "Défaut antivol de direction : Faites réparer le véhicule",
        37 to "Défaut antidémarrage electronique",
        39 to "Manoeuvre de toit impossible : Température système trop élevée",
        40 to "Manoeuvre du toit impossible : Démarrer le moteur",
        41 to "Manoeuvre du toit impossible : Serrez le frein à main",
        42 to "Défaut système hybride : Arrêtez le véhicule, consultez notice",
        43 to "Défaut réglage automatique des projecteurs",
        44 to "Défaut système hybride : Faites réparez le véhicule",
        45 to "Défaut système hybride : Vitesse limitée, faites réparer le véhicule",
        46 to "Ajustez niveau liquide lave glace",
        47 to "Remplacez la pile de la telecommande",
        49 to "Préchauffage : préventilation désactivé : Réglez l'horloge",
        50 to "Défaut connexion remorque : Faites réparer le véhicule",
        52 to "Défaut surveillance de sous gonflage",
        53 to "Radar de suivi sale : nettoyez-le",
        57 to "Mode Electrique indisponible : régénération FAP en cours",
        59 to "Crevaison roue avant gauche : Remplacez ou réparez la roue",
        60 to "Crevaison roue avant droite : Remplacez ou réparez la roue",
        61 to "Crevaison roue arrière droite : Remplacez ou réparez la roue",
        62 to "Crevaison roue arrière gauche : Remplacez ou réparez la roue",
        63 to "Controlez les feux de position",
        64 to "Controlez les feux de position",
        65 to "Controlez les feux de position",
        66 to "Controlez les feux de position",
        71 to "Controlez feu stop ARD",
        72 to "Controlez feu stop ARG",
        73 to "Contrôlez les feux antibrouillard avant droit",
        74 to "Contrôlez les feux antibrouillard avant gauche",
        75 to "Contrôlez les feux antibrouillard arriere gauche",
        76 to "Contrôlez les feux antibrouillard arriere droit",
        77 to "Controlez les feux indicateurs de direction",
        78 to "Controlez les feux indicateurs de direction",
        79 to "Controlez les feux indicateurs de direction",
        80 to "Controlez les feux indicateurs de direction",
        81 to "Controlez les feux de recul",
        82 to "Controlez les feux de recul",
        91 to "Défaut système aide au stationnement",
        94 to "Roue avant gauche sous gonflée : Ajustez la pression des pneus",
        95 to "Roue avant droite sous gonflée : Ajustez la pression des pneus",
        96 to "Roue arrière droite sous gonflée : Ajustez la pression des pneus",
        97 to "Roue arrière gauche sous gonflée : Ajustez la pression des pneus",
        98 to "Eteignez les feux",
        100 to "Défaut antipollution : Démarrage interdit dans xxxx km",
        101 to "Défaut antipollution : Démarrage interdit",
        102 to "Défaut antipollution",
        106 to "Placez boite automatique en position \"P\"",
        107 to "Risque de verglas",
        108 to "Porte avant droite ouverte",
        109 to "Porte avant gauche ouverte",
        110 to "Porte arrière droite ouverte",
        111 to "Porte arrière gauche ouverte",
        112 to "Coffre ouvert",
        113 to "Défaut système de détection du risque de collision",
        114 to "Lunette arrière ouverte",
        123 to "Défaut frein de parking : Faites réparez le véhicule",
        124 to "Aileron mobile défaillant, Vitesse limitée, Consultez la notice",
        125 to "Défaut système de freinage automatique",
        126 to "Défaut projecteurs directionnels",
        133 to "Défaut boite de vitesse : Faites réparez le vehicule",
        141 to "Défaut moteur : Faites réparer le véhicule",
        142 to "Défaut suspension : Limitez votre vitesse",
        148 to "Défaut capteur : Pression pneu avant gauche non surveillée",
        149 to "Défaut capteur : Pression pneu avant droit non surveillée",
        150 to "Défaut capteur : Pression pneu arrière droit non surveillée",
        151 to "Défaut capteur : Pression pneu arrière gauche non surveillée",
        153 to "Défaut direction assistée : Faites réparez le véhicule",
        156 to "Défaut mesure du temps inter-véhicule",
        157 to "Défaut moteur : arrêtez le véhicule",
        159 to "Défaut surveillance de sous gonflage",
        160 to "Roue arrière droite sous gonflée : ajustez pression pneus, puis reinit",
        161 to "Roue arrière gauche sous gonflée : ajustez pression pneus, puis reinit",
        162 to "Roue avant droite sous gonflée : ajustez pression pneus, puis reinit",
        163 to "Roue arrière gauche sous gonflée : ajustez pression pneus, puis reinit",
        164 to "Freinage automatique désactivé",
        165 to "Remplir additif antipollution : Demarrage interdit dans xxxx km",
        166 to "Remplir additif antipollution : Demarrage interdit dans xxxx km",
        167 to "Remplir additif antipollution : Demarrage interdit"
    )

    private val CATALOG: Map<Int, AlertInfo> = mapOf(
        0 to AlertInfo("Pressione olio motore anomala", "Abnormal engine oil pressure", "HIGH"),
        1 to AlertInfo("Temperatura motore troppo elevata", "Engine temperature too high", "HIGH"),
        3 to AlertInfo("Anomalia impianto frenante", "Faulty braking system", "HIGH"),
        5 to AlertInfo("Anomalia servosterzo", "Faulty power steering", "MEDIUM"),
        6 to AlertInfo("Livello liquido di raffreddamento insufficiente", "Cooling circuit level too low", "HIGH"),
        8 to AlertInfo("Livello olio motore insufficiente", "Engine oil level too low", "HIGH"),
        17 to AlertInfo("Anomalia ESP / ASR", "Faulty ESP/ASR", "MEDIUM"),
        18 to AlertInfo("Anomalia batteria", "Faulty battery", "HIGH"),
        20 to AlertInfo("Anomalia del filtro gasolio", "Faulty diesel filter", "HIGH"),
        21 to AlertInfo("Stadio avanzato di usura delle pastiglie dei freni", "Advanced wear of brake pads", "MEDIUM"),
        22 to AlertInfo("Livello carburante basso", "Fuel level low", "HIGH"),
        23 to AlertInfo("Anomalia Airbag", "Faulty airbag(s)", "MEDIUM"),
        25 to AlertInfo("Anomalia del sistema antinquinamento", "Faulty emission control system", "HIGH"),
        26 to AlertInfo("Anomalia ABS", "Faulty ABS", "MEDIUM"),
        27 to AlertInfo("Rischio di intasamento del filtro antiparticolato (FAP)", "Risk of particle filter clogging", "HIGH"),
        29 to AlertInfo("Livello additivo del filtro antiparticolato insufficiente", "Particle filter additive level too low", "HIGH"),
        31 to AlertInfo("Anomalia al sistema delle sospensioni", "Faulty suspension system"),
        36 to AlertInfo("Anomalia bloccasterzo", "Faulty steering lock system"),
        37 to AlertInfo("Anomalia dell'antiavviamento elettronico", "Faulty electronic immobilizer", "HIGH"),
        38 to AlertInfo("Livello olio troppo alto", "Oil level too high"),
        43 to AlertInfo("Anomalia regolazione automatica dei fari", "Faulty automatic headlight adjustment", "MEDIUM"),
        44 to AlertInfo("Anomalia del sistema di trazione ibrida", "Faulty hybrid system"),
        45 to AlertInfo("Anomalia del sistema di trazione ibrida", "Faulty hybrid system"),
        46 to AlertInfo("Livello liquido lavacristalli insufficiente", "Windscreen washer fluid level too low", "HIGH"),
        52 to AlertInfo("Pressione pneumatico/i insufficiente", "Tyre pressure too low", "MEDIUM"),
        53 to AlertInfo("Sensore radar di guida sporco", "Tracking radar dirty"),
        59 to AlertInfo("Pressione pneumatico/i insufficiente", "Tyre pressure too low", "MEDIUM"),
        60 to AlertInfo("Pressione pneumatico/i insufficiente", "Tyre pressure too low", "MEDIUM"),
        61 to AlertInfo("Pressione pneumatico/i insufficiente", "Tyre pressure too low", "MEDIUM"),
        62 to AlertInfo("Pressione pneumatico/i insufficiente", "Tyre pressure too low", "MEDIUM"),
        63 to AlertInfo("Anomalia lampadina/e luci di posizione (Anteriore Sinistra)", "Faulty side marker light bulb(s) (Front Left)", "MEDIUM"),
        64 to AlertInfo("Anomalia lampadina/e luci di posizione (Anteriore Destra)", "Faulty side marker light bulb(s) (Front Right)", "MEDIUM"),
        65 to AlertInfo("Anomalia lampadina/e luci di posizione (Posteriore Destra)", "Faulty side marker light bulb(s) (Rear Right)", "MEDIUM"),
        66 to AlertInfo("Anomalia lampadina/e luci di posizione (Posteriore Sinistra)", "Faulty side marker light bulb(s) (Rear Left)", "MEDIUM"),
        67 to AlertInfo("Anomalia anabbaglianti", "Faulty dipped beams", "MEDIUM"),
        68 to AlertInfo("Anomalia anabbaglianti", "Faulty dipped beams", "MEDIUM"),
        69 to AlertInfo("Anomalia abbaglianti", "Faulty full beams", "MEDIUM"),
        70 to AlertInfo("Anomalia abbaglianti", "Faulty full beams", "MEDIUM"),
        71 to AlertInfo("Anomalia lampadina stop Posteriore Destra", "Faulty rear right brake light bulb", "MEDIUM"),
        72 to AlertInfo("Anomalia lampadina stop Posteriore Sinistra", "Faulty rear left brake light bulb", "MEDIUM"),
        73 to AlertInfo("Anomalia fendinebbia", "Faulty foglights", "MEDIUM"),
        74 to AlertInfo("Anomalia fendinebbia Anteriori", "Faulty front foglights", "MEDIUM"),
        75 to AlertInfo("Anomalia lampadina/e fendinebbia Posteriori Destra", "Faulty rear right foglight bulb(s)", "MEDIUM"),
        76 to AlertInfo("Anomalia lampadina/e fendinebbia Posteriori", "Faulty rear foglight bulb warning", "MEDIUM"),
        77 to AlertInfo("Anomalia indicatore/i di direzione (Anteriore Destro)", "Faulty indicator(s) (Front Right)", "MEDIUM"),
        78 to AlertInfo("Anomalia indicatore/i di direzione (Posteriore Destro)", "Faulty indicator(s) (Rear Right)", "MEDIUM"),
        79 to AlertInfo("Anomalia indicatore/i di direzione (Anteriore Sinistro)", "Faulty indicator(s) (Front Left)", "MEDIUM"),
        80 to AlertInfo("Anomalia indicatore/i di direzione (Posteriore Sinistro)", "Faulty indicator(s) (Rear Left)", "MEDIUM"),
        81 to AlertInfo("Anomalia luce di retromarcia", "Faulty reverse light", "MEDIUM"),
        82 to AlertInfo("Anomalia lampadina luce di retromarcia", "Faulty reverse light bulb", "MEDIUM"),
        91 to AlertInfo("Anomalia sistema di parcheggio assistito", "Faulty parking aid system", "HIGH"),
        94 to AlertInfo("Pressione pneumatico/i insufficiente", "Tyre pressure too low", "MEDIUM"),
        95 to AlertInfo("Pressione pneumatico/i insufficiente", "Tyre pressure too low", "MEDIUM"),
        96 to AlertInfo("Pressione pneumatico/i insufficiente", "Tyre pressure too low", "MEDIUM"),
        97 to AlertInfo("Pressione pneumatico/i insufficiente", "Tyre pressure too low", "MEDIUM"),
        100 to AlertInfo("Anomalia antinquinamento", "Faulty emission control system"),
        101 to AlertInfo("Anomalia antinquinamento", "Faulty emission control system"),
        102 to AlertInfo("Anomalia antinquinamento", "Faulty emission control system"),
        123 to AlertInfo("Anomalia sistema freno di stazionamento", "Faulty hand brake system", "MEDIUM"),
        126 to AlertInfo("Anomalia luce/i di curva", "Faulty directional headlight(s)", "MEDIUM"),
        133 to AlertInfo("Anomalia al cambio", "Faulty gearbox", "HIGH"),
        141 to AlertInfo("Malfunzionamento generale del motore", "General engine dysfunction", "HIGH"),
        142 to AlertInfo("Anomalia della sospensione", "Faulty suspension", "HIGH"),
        148 to AlertInfo("Pressione pneumatico insufficiente", "Tyre pressure too low", "MEDIUM"),
        149 to AlertInfo("Pressione pneumatico insufficiente", "Tyre pressure too low"),
        150 to AlertInfo("Pressione pneumatico insufficiente", "Tyre pressure too low"),
        151 to AlertInfo("Pressione pneumatico insufficiente", "Tyre pressure too low"),
        152 to AlertInfo("Anomalia della sospensione", "Faulty suspension", "MEDIUM"),
        153 to AlertInfo("Anomalia servosterzo", "Faulty power steering", "MEDIUM"),
        157 to AlertInfo("Anomalia motore", "Faulty engine"),
        159 to AlertInfo("Anomalia monitoraggio pressione pneumatici", "Faulty under-inflation monitoring system"),
        160 to AlertInfo("Pneumatico posteriore destro sgonfio", "Under-inflated rear right tyre"),
        161 to AlertInfo("Pneumatico posteriore sinistro sgonfio", "Under-inflated rear left tyre"),
        162 to AlertInfo("Pneumatico anteriore destro sgonfio", "Under-inflated front right tyre"),
        163 to AlertInfo("Pneumatico anteriore sinistro sgonfio", "Under-inflated front left tyre"),
        165 to AlertInfo("Livello additivo antinquinamento insufficiente", "Emission control additive level too low"),
        166 to AlertInfo("Livello additivo antinquinamento insufficiente", "Emission control additive level too low"),
        167 to AlertInfo("Livello additivo antinquinamento insufficiente", "Emission control additive level too low")
    )

    fun lookup(code: Int): AlertInfo? = CATALOG[code]

    fun title(code: Int, language: String? = Locale.getDefault().language): String? {
        val info = lookup(code)
        if (language == "fr") return HU_FR[code] ?: info?.titleEn
        return when {
            info != null -> if (language == "it") info.titleIt else info.titleEn
            else -> HU_FR[code]
        }
    }

    fun criticity(code: Int): String? = lookup(code)?.criticity
}
